# Generated by Django 3.2 on 2020-05-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='probar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='cago en todo', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Titulo de la serie', max_length=100, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ImagenPortada', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Titulo del video', max_length=100, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('video', models.FileField(default='default.mp4', upload_to='')),
                ('serie', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='videos.series')),
            ],
        ),
    ]
